### ISSUE TITLE
Integration with IntelliJ

### ISSUE THREAD

**Issue by WamBamBoozle** [dcoker/cfpp#3]
This is wonderful stuff. Tragically, IntelliJ doesn't understand it so I get a bunch of undefined warnings in the editor.

**Comment by dcoker** [comment]
Thanks for the feedback!

The ability to whitelist custom prefixes (such as `CFPP::`) sounds like a great feature request for the IntelliJ [CloudFormation plugin](https://github.com/shalupov/idea-cloudformation/issues) project.
